# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    email_validation:
       class: AppBundle\Manager\EmailValidation
       autowire: true